### PR TITLE
fix: handle React 19 legacy peer deps

### LINKED ISSUE #49: Use --legacy-peer-deps when React 19 is installed
Users who are using a React 19 installation need to run their install command with --legacy-peer-deps, we should detect and run this automatically for them.

### PR DESCRIPTION
**Pull request by jonathanlab**
Closes #49 

Also checked whether other package managers need to handle this, but seems like `npm` is the only package manager that does not spark joy when using React 19 with older peer dependencies. If it turns out that this isn't the case, we can move this type of flag to the `PackageManager` interface.

### CODE REVIEW

File: src/utils/clack-utils.ts [hunk 1]
```diff
@@ -255,6 +256,27 @@ export async function confirmContinueIfPackageVersionNotSupported({
...
+    const packageJson = await getPackageDotJson({ installDir });
+    const reactVersion = getPackageVersion('react', packageJson);
+
+    if (!reactVersion) {
+      return false;
+    }
+
+    return fulfillsVersionRange({
+      version: reactVersion,
+      acceptableVersions: '>=19.0.0',
```
Comment (joshsny) [inline src/utils/clack-utils.ts:270]: this will match v20 I think, do we want that?

**Review by joshsny — APPROVED** [review]
Nice!

File: src/utils/clack-utils.ts (hunk 1 above)
Comment (jonathanlab) [reply src/utils/clack-utils.ts:270]: Yeah I considered that this problem will very likely occur in the future on newer React versions as well. I can make it only check for V19 if you think that's a safer bet :)

Comment (joshsny) [reply src/utils/clack-utils.ts:270]: yeah likely will, let's keep it :)
